.github/workflows/build.yml
.github/workflows/deploy.yml

This PR re-adds the GitHub Actions workflow for deployment, as well as a build workflow to test that the application can build on each push to the repo.

Re-enable actions

---

package-lock.json
package.json

This reverts commit 8f5fe8d35070480d16de414cc996b12884ab062a.
(Causes Gatsby build failures)

Revert "fix(deps): npm audit fix"

---

src/components/nav.js

Support -> Community to match update in landing page nav

Update nav content to match landing page

---

gatsby-config.js
src/components/seo.js

Add social/og images

---

src/components/bookmark_state.js
src/utils.js

Fixes #10 by closing some console warnings

Clean up some hooks deps usage

---

sanity/schemas/collection.js
src/pages/built-with.js
src/templates/project.js
src/utils.js

Fixes #96, fixes #62, fixes #31

Remove features from collections, simplify normalization code

---

gatsby-browser.js
src/components/project.js
src/components/route-update-history.js
src/pages/built-with.js

It turns out https://github.com/cloudflare/workers.cloudflare.com/pull/94 didn’t really do what we thought it did.
This should actually work.
cc @signalnerve

Only show bookmarks fading in on hard page load

---

gatsby-config.js
package-lock.json
package.json

closes #111
@dragosbogdan please follow up in chat tomorrow, i have this turned on locally so we can confirm that things are working as expected, then we can merge :)

re-add google tag manager integration

---

src/pages/index.js

Update to use wrangler login!

---

src/components/footer.js
src/components/nav.js

Add links to our new Discord community in the header and footer of the site

Add Discord links

---

workers-site/index.js
workers-site/package-lock.json
workers-site/package.json
workers-site/redirects.js

Add lilredirector and `redirects.js` to fix https://github.com/cloudflare/cloudflare-docs/issues/11. Also bumps kv-asset-handler to a more recent version

Add lilredirector

---

package-lock.json
package.json
src/pages/works.js

This commit brings twind in as a module, switches the page to tailwind-in-js, and removes the FOUC by waiting for the component to render before making it visible

Fix FOUC on works page

---

src/pages/index.js

sry for diff, VS Code has feelings

Update pricing name to Paid

---

src/pages/index.js

Remove Full Stack Week notice

---

src/pages/node.js

Merge after https://github.com/cloudflare/cloudflare-docs/pull/8171

Clarify current support for node.js APIs

---

src/pages/index.js

Update publish text on Workers homepage

---

README.md
sanity/schemas/link.js
sanity/scripts/renameField.js
src/components/bookmark_icon.js
src/components/bookmark_state.js
src/components/content-page.js
src/components/edge_state.js
src/components/footer.js
src/components/icon.js
src/components/markdown.js
src/components/nav.js
src/components/notice.js
src/components/project.js
src/components/route-update-history.js
src/components/seo.js
src/html.js
src/pages/404.js
src/pages/built-with.js
src/pages/index.js
src/pages/node.js
src/pages/search.js
src/templates/collection.js
src/templates/feature.js
src/templates/project.js
src/utils.js

Change primary CTA to the Workers Playground

Playground surfacing

---

src/pages/index.js

Refs recent feedback, language on `workers.cloudflare.com` is outdated / wasn't accurate. Limit here is on CPU time, not duration.

Clarify CPU time limit on Paid plan

---

app/components/markdown.jsx
app/routes/built-with.projects.$slug.jsx

Fix feature list on project pages

---

app/components/markdown.jsx
app/lib/sanity/index.ts
app/routes/built-with.projects.$slug.jsx
package-lock.json
package.json
sanity/schemaTypes/project.js

Add support for Cloudflare Stream IDs to show videos on project pages in Built With section

[built with] Video embeds

---

app/components/footer.jsx
app/root.tsx
app/styles/footer.css

- Remove non-working googletagmanager and gtag scripts
- Remove green background-color on privacy button
- Fix icon now opens consent modal

Fix consent icon and button
